name: Serverless Devs Project CI/CD

on:
  push:
    branches: [main]

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: scf inject
        run: npm install -g serverless-cloud-framework@latest
      - name: env injected and start deploy
        run: scf deploy
        env:
          TENCENT_SECRET_ID: ${{secrets.ACCESSID}}
          TENCENT_SECRET_KEY: ${{secrets.ACCESSKEY}}
